name: bagit
description: "e-commerce App"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Utility Specific
  connectivity_plus: ^6.0.5
  flutter_native_splash: ^2.4.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  logger: ^2.4.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.0

  # Product Specific
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  readmore: ^3.0.0

  # Firebase
  cloud_firestore: ^5.4.1
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  firebase_storage: ^12.3.0
  google_sign_in: ^6.2.1

  # Undefined
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  firebase_app_check: ^0.3.1+1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/categories/
    - assets/icons/user/
    - assets/icons/payment_methods/
    - assets/images/banners/
    - assets/images/logo/
    - assets/images/lottie/
    - assets/images/onboarding/
    - assets/images/others/
    - assets/images/products/
    - assets/images/reviews/
