name: buy_it_app
description: "e-commerce App"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  flutter_rating_bar: ^4.0.0
  flutter_form_builder: ^8.0.0
  flutter_paytabs_bridge: ^2.6.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
