// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-b0nNKFuN7kuDRPlTlwRfm6df1IwmC0U',
    appId: '1:367126395524:web:b0d46336d007096e15a0d1',
    messagingSenderId: '367126395524',
    projectId: 'bagit-e-commerce-app',
    authDomain: 'bagit-e-commerce-app.firebaseapp.com',
    storageBucket: 'bagit-e-commerce-app.appspot.com',
    measurementId: 'G-R9G74G8EBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-oau8nrkivvwXk4kQ-hR7aVsTh6YmCvo',
    appId: '1:367126395524:android:13b9ace6bd0cdd1715a0d1',
    messagingSenderId: '367126395524',
    projectId: 'bagit-e-commerce-app',
    storageBucket: 'bagit-e-commerce-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb4OHPnhL-aT_IfA0iXqDZz2ReSnfdXwE',
    appId: '1:367126395524:ios:751ad52c84a79b8b15a0d1',
    messagingSenderId: '367126395524',
    projectId: 'bagit-e-commerce-app',
    storageBucket: 'bagit-e-commerce-app.appspot.com',
    iosBundleId: 'com.example.buyItApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb4OHPnhL-aT_IfA0iXqDZz2ReSnfdXwE',
    appId: '1:367126395524:ios:751ad52c84a79b8b15a0d1',
    messagingSenderId: '367126395524',
    projectId: 'bagit-e-commerce-app',
    storageBucket: 'bagit-e-commerce-app.appspot.com',
    iosBundleId: 'com.example.buyItApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-b0nNKFuN7kuDRPlTlwRfm6df1IwmC0U',
    appId: '1:367126395524:web:4db4ac000f1fe65e15a0d1',
    messagingSenderId: '367126395524',
    projectId: 'bagit-e-commerce-app',
    authDomain: 'bagit-e-commerce-app.firebaseapp.com',
    storageBucket: 'bagit-e-commerce-app.appspot.com',
    measurementId: 'G-4F5Z87CPR8',
  );
}
